packages:
  - examples/*
  - scripts/*

onlyBuiltDependencies:
  - esbuild
  - puppeteer

catalog:
  typescript: ~5.9.3

includeWorkspaceRoot: true

publicHoistPattern:
  - '@oxc-project/types' # we need rolldown's exact version but they don't re-export

