on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --lockfile-only
      - run: pnpm run build
      - run: pnpm run --recursive check
